.travis.yml

Try adding
- CFLAGS=$CFLAGS" -Wno-sign-compare -Wno-unused-result"
to before_install instructions in .travis.yml

MAINT: Fix warning errors on Python3.

---

.appveyor.yml

The wheel was pinned to version 0.16 because later versions did not work
on windows. That may no longer be the case and we would like to have the
full, detailed wheel names.
See https://github.com/numpy/numpy/issues/11508.

Unpin the appveyor wheel version

---

.appveyor.yml
.travis.yml

Cython >= 0.29.2 is needed to avoid memory leaks.

Update Cython version.

---

.appveyor.yml
config.sh
env_vars.sh

This is motivated by an OpenBLAS-related issue in https://github.com/numpy/numpy/issues/13173, where it was suggested we should bump wheels to use the latest OpenBLAS release point, `v0.3.5`, instead of an earlier development commit on the path to that release (`0.3.5.dev`).
This follows the upstream [merging of the version bump PR for OpenBLAS binaries](https://github.com/MacPython/openblas-libs/pull/1) & the uploads to community server.

Bump OpenBLAS to v0.3.5 release point

---

config.sh

Related to #22, at least for Linux--both 32 and 64-bit Docker containers seem to be missing `gfortran` there. Mac doesn't seem to have this problem at the moment.
If this works, all linux tests should adjust from having 500+ skips to a more reasonable number of skips, irrespective of the sporadic failure or 32/64-bit status.
I also find the comment above my changes to be confusing:
> We only run the 64 bit tests as of NumPy 1.16.
Especially since I've been trying to debug the sporadic `Pinv` issue again on a private repo with debug / interactive Travis mode. I'll see if I can figure out what changes are associated with that comment. The `complex64` failure had me thinking about `m32` compile / link flags again as well.
Perhaps the comment refers to Mac, but that is confusing given the …

MAINT: install gfortran on linux

---

.appveyor.yml
env_vars.sh

Bump OpenBLAS version based on the (emulated) fix demonstration for SkylakeX NumPy linalg issues in: https://github.com/numpy/numpy/pull/13466
The NumPy release manager may also want to cherry-pick this to the 1.16.x wheels branch if it looks suitable / justified.
* this version of OpenBLAS includes proper
deactivation of problematic AVX routines
reported to cause issues for NumPy linalg
on SkylakeX architecture

MAINT: Bump OpenBLAS to 0.3.7.dev

---

.appveyor.yml
.gitignore
openblas_support.py

Part of the fix for numpy/numpy#13764, the other part (removing code from `numpy/core/__init__.py` and duplicating this code there) has to be done in the numpy repo after this is merged in order to reuse `openblas_support.py` from here.
This creates a `_distributor_local.py` file which is packaged with the wheel (on windows only).
I named the new file `openblas_support.py` in the hope that we can add some of the environment variables to it which might unify some of the travis/appveyor/future azure/ CI behaviour

BUILD: add _distributor_local.py to  preload dll on windows

---

.appveyor.yml
openblas_support.py

Fix for #50: it was writing `_distributor_init.py` to the wrong directory. Also fix a typo.
Closes #49

BUG: fix base directory and typo

---

openblas_support.py

Closes #49 (third time is the charm).
copy-paste error.
The `_distributor_init.py` file is at the root directory, the original code was one directory down.

BUG: final file location is at numpy root directory

---

.appveyor.yml
env_vars.sh

* build NumPy wheels with latest stable release of OpenBLAS,
`v0.3.7`, instead of using a commit hash on the development
branch prior to that release

MAINT: bump OpenBLAS to v0.3.7 stable

---

.travis.yml

This is to check out the downstream response. Note that pip >= 19.0 is required, but for nightly builds this may not have an effect because there are already manylinux1 wheels available. Perhaps we should delete them? We many want to upload both manylinux versions after the 1.19.0 release if there are excessive pip problems.

Use manylinux2010 instead of default manylinux1.

---

.appveyor.yml
.travis.yml
README.rst
config.sh
env_vars_32.sh

test latest version of tools before adding new platforms, also check openblas is properly installed

update submodules to latest versions

---

README.rst
azure-pipelines.yml
azure/posix.yml

PR gh-78 was merged, we now have manylinux2010 wheels on anaconda.org. I thought we could convert manylinux2010 to manylinux1, but that was not correct. If we want manylinux1 wheels, we must add azure jobs to do so
This PR adds 6 more jobs to build manylinux1 for python3.6, 3.7, 3.8; 32 and 64 bit. It also fixes the README for the new wheel locations.

fixup readme, add manylinux1 wheels

---

azure/posix.yml
azure/windows.yml
env_vars_32.sh

Checking if removing the -msse2 flag from 32-bit fixes wheel building. Should revert this once the last 1.18 build is done, since the problem is fixed on master and the flag allows faster loops.

WIP: remove -msse2 from linux32 builds, use explicit build tag

---

README.rst

Some further updates for the new azure/anaconda build machinery.

DOC: Update the README.rst file for azure pipelines.

---

azure/posix.yml
azure/windows.yml
extra_functions.sh

xref pandas-dev/pandas#33968
I didn;t notice that the wheeluploader used for rackspace modifies the wheel name so that later names will be picked up by pip before earlier ones. Since the wheels now have timetags, there should not be collisions so I also removed the `--force`.

add a date to make the dev wheels sortable

---

env_vars.sh
env_vars_32.sh

Replaces gh-82 : we should strip the linux binaries before shipping. 
Issue gh-19 assumed that we do not override CFLAGS, but we do. Using a branch on a fork so successful builds are not uploaded

Append flags

---

.travis.yml
azure/posix.yml
azure/windows.yml

missed this in gh-84: we only want to add the date to the wheels at https://anaconda.org/scipy-wheels-nightly/numpy/files, since the ones at https://anaconda.org/multibuild-wheels-staging/numpy/files are meant to be PyPI candidates. Note that since this PR is from a fork, the changes will not be tested.

only rename wheels that go to scipy-wheels-nightly

---

azure-pipelines.yml

Removing the trigger section enables triggering on every branch. This was needed for
the 1.19.0rc1 release. Curiously, the numpy/numpy pipeline was triggered instead before
this change.

Remove trigger section from azure-pipeline

---

.travis.yml
azure-pipelines.yml
azure/posix.yml

Let's try this. manylinux has support, but maybe the test images do not (on linux). The chances Azure supports it for macOS and windows are slim.

add python 3.9

---

.travis.yml

This is needed so that versioneer can find the latest tag as the number
of commits in master continue to grow.

MAINT: Disable TravisCI clone depth.

---

azure-pipelines.yml

Start using manylinux2014 for nightly builds in preparation for NumPy 1.22.x.

MAINT: Drop manylinux1 and manylinux2010 wheels in main.

---

.travis.yml
azure-pipelines.yml
azure/windows.yml
config_ilp64.sh

Summary of current problems
-  Windows: Flaky, seem to depend on whether or not mingw gcc compiler is found by distutils. May be a distutils problem.
-  Mac: universal2 fails, seems to be a problem finding the downloaded ILP64 arm64 library.
-  Arm64 (travis): looks like a bug in the OpenBLAS library, hangs testing dot product. 
This PR does not enable ILP64 for universal2 and travis arm64 wheel builds, those problems are left for later PRs.

MAINT: Use BLAS ILP64 for 64 bit wheels

---

azure-pipelines.yml
azure/windows.yml

Small fixes:
- ENV_VARS_PATH was accidentally removed from 32 bit linux builds
- Improve azure/windows.yml script
This fixes the Windows openblas64_ builds' flakyness. They would randomly fail before.

BUG: Windows and Linux build fixes

---

.gitmodules
azure-pipelines.yml

- Change multibuild submodule to point to multi-built/multibuid instead
of Matthew's fork in order to get latest merges.
- Update multibuild to HEAD of devel
- Add thin x86_64 thin wheel build for Mac.

MAINT: Update for 3.10 on Mac

---

azure-pipelines.yml
azure/set_vs_toolchain.cmd
azure/windows.yml

See discussion at https://github.com/MacPython/numpy-wheels/issues/145
I'm afraid I can't test this because I don't have Azure Pipeline permissions
for my own account.
Do I need some permissions from y'all?

Use 141 toolchain for Windows build

---

azure/posix.yml
env_vars.sh
env_vars_32.sh

This is needed because of changes in the azure provided Python 3.8 for
Mac.

Update Mac version from 10.9 to 10.14.

---

azure/set_vs_toolchain.cmd

See: https://github.com/MacPython/numpy-wheels/pull/146#discussion_r792910164

Add conda-forge license note

---

azure-pipelines.yml
azure/posix.yml
azure/set_vs_toolchain.cmd
azure/windows.yml
env_vars.sh
env_vars_32.sh

This is a backport of #146, #149, #150 in order to fix the following:
- Change the vs2019 tool chain to 1.41 to allow downstream extensions built with 1.41 to link with NumPy provided libraries.
- Update the Mac os version from 10.9 to 10.14. That is the oldest Apple supported version and is needed due to azure updates.

Backport build fixes from main.

---

azure-pipelines.yml

We still need this repo for the release, but can stop the weekly cron job since the main repo is now running a cron job via cibuildwheel. If this PR is accepted, I will also stop the travis cron job (via the travis GUI).

stop the azure cron job now that cibuildwheel is uploading

---

.travis.yml
azure/posix.yml
env_vars.sh
env_vars_32.sh

Keep main updated in case we need to fall back to it. @mattip Do we still need travis for aarch64?

MAINT: Update Cython versions to 0.29.30.
